### PR TITLE
I believe it is working

### PR DESCRIPTION
**Pull request by akibrhast**
## Overview
This PR creates a django command `python manage.py toggle`.
The toggle command queries the github api for all repositories which has the topic:civictechindex. 
It loops through the entire database organization table.
- For any matching organization name from the api call that exist in the database
    - it sets the cti_contributor column value to true
- For organization name in the database that does not exist in the rv of the api call
    - it sets the cti_contributor column value to true
- Lastly for any organization name from the api call that does not exist in the db
    - it adds those organization to the database and set their cti_contributor status to true.

## toggle function logs
```bash
root@c27c5c39fa43:/code# cat manage_toggle.log
INFO: 2021-05-01 05:55:56,904 ==========Script Start==========
INFO: 2021-05-01 05:56:05,187 civictechindex ogranizations from api call -> [['100 Automations', 'BetaNYC', 'Civic Tech Index', 'Code for Buffalo', 'Code for Chapel Hill', 'Code for PDX', 'Code for Tulsa', 'EnCiv', 'Hack for LA', "Hack for LA's Sandbox", 'OpenOakland', 'Yale OpenLab']]
INFO: 2021-05-01 05:56:05,201 org [BetaNYC] in database exist in org name from api and db value is false, so it is being set to true
INFO: 2021-05-01 05:56:05,212 org [Code for Buffalo] in database exist in org name from api and db value is false, so it is being set to true
INFO: 2021-05-01 05:56:05,215 org [Code for Chapel Hill] in database exist in org name from api and db value is false, so it is being set to true
INFO: 2021-05-01 05:56:05,217 org [Code for PDX] in database exist in org name from api and db value is false, so it is being set to true
INFO: 2021-05-01 05:56:05,219 org [Code for Tulsa] in database exist in org name from api and db value is false, so it is being set to true
INFO: 2021-05-01 05:56:05,221 org [Hack for LA] in database exist in org name from api and db value is false, so it is being set to true
INFO: 2021-05-01 05:56:05,223 Created new issue for organization [['100 Automations', 'Civic Tech Index', 'EnCiv', "Hack for LA's Sandbox", 'OpenOakland', 'Yale OpenLab']]
INFO: 2021-05-01 05:56:05,224 ==========Script End==========
INFO: 2021-05-01 05:56:08,498 ==========Script Start==========
INFO: 2021-05-01 05:56:15,772 civictechindex ogranizations from api call -> [['100 Automations', 'BetaNYC', 'Civic Tech Index', 'Code for Buffalo', 'Code for Chapel Hill', 'Code for PDX', 'Code for Tulsa', 'EnCiv', 'Hack for LA', "Hack for LA's Sandbox", 'OpenOakland', 'Yale OpenLab']]
INFO: 2021-05-01 05:56:15,785 org [BetaNYC] in database exist in org name from api and db value is true, remove org from civictechindex_org_container
INFO: 2021-05-01 05:56:15,785 org [Code for Buffalo] in database exist in org name from api and db value is true, remove org from civictechindex_org_container
INFO: 2021-05-01 05:56:15,786 org [Code for Chapel Hill] in database exist in org name from api and db value is true, remove org from civictechindex_org_container
INFO: 2021-05-01 05:56:15,786 org [Code for PDX] in database exist in org name from api and db value is true, remove org from civictechindex_org_container
INFO: 2021-05-01 05:56:15,786 org [Code for Tulsa] in database exist in org name from api and db value is true, remove org from civictechindex_org_container
INFO: 2021-05-01 05:56:15,787 org [Hack for LA] in database exist in org name from api and db value is true, remove org from civictechindex_org_container
INFO: 2021-05-01 05:56:15,787 Created new issue for organization [['100 Automations', 'Civic Tech Index', 'EnCiv', "Hack for LA's Sandbox", 'OpenOakland', 'Yale OpenLab']]
INFO: 2021-05-01 05:56:15,787 ==========Script End==========
INFO: 2021-05-01 05:56:18,342 ==========Script Start==========
INFO: 2021-05-01 05:56:25,377 civictechindex ogranizations from api call -> [['100 Automations', 'BetaNYC', 'Civic Tech Index', 'Code for Buffalo', 'Code for Chapel Hill', 'Code for PDX', 'Code for Tulsa', 'EnCiv', 'Hack for LA', "Hack for LA's Sandbox", 'OpenOakland', 'Yale OpenLab']]
INFO: 2021-05-01 05:56:25,386 org [BetaNYC] in database exist in org name from api and db value is true, remove org from civictechindex_org_container
INFO: 2021-05-01 05:56:25,386 org [Code for Buffalo] in database exist in org name from api and db value is true, remove org from civictechindex_org_container
INFO: 2021-05-01 05:56:25,387 org [Code for Chapel Hill] in database exist in org name from api and db value is true, remove org from civictechindex_org_container
INFO: 2021-05-01 05:56:25,387 org [Code for PDX] in database exist in org name from api and db value is true, remove org from civictechindex_org_container
INFO: 2021-05-01 05:56:25,387 org [Code for Tulsa] in database exist in org name from api and db value is true, remove org from civictechindex_org_container
INFO: 2021-05-01 05:56:25,387 org [Hack for LA] in database exist in org name from api and db value is true, remove org from civictechindex_org_container
INFO: 2021-05-01 05:56:25,388 Created new issue for organization [['100 Automations', 'Civic Tech Index', 'EnCiv', "Hack for LA's Sandbox", 'OpenOakland', 'Yale OpenLab']]
INFO: 2021-05-01 05:56:25,388 ==========Script End==========
```
## db output
```bash
cti=# SELECT id,name,github_name,cti_contributor FROM data_organization WHERE cti_contributor='t';
 id  |         name         |     github_name      | cti_contributor
-----+----------------------+----------------------+-----------------
  40 | Code for Tulsa       | codefortulsa         | t
  18 | Code for Buffalo     | CodeForBuffalo       | t
  41 | Code for PDX         | codeforpdx           | t
 124 | Hack for LA          | hackforla            | t
  17 | BetaNYC              | betanyc              | t
  22 | Code for Chapel Hill | code-for-chapel-hill | t
(6 rows)

```

### CODE REVIEW

**Review by cnk — CHANGES_REQUESTED** [review]
Overall nice work. I am not sure how useful it is to log to a file. It's less convenient than writing to stdout while running this by hand and not very useful in the intended production environment which is transient containers on FARGATE. How about converting your logging to self.stdout.write('some message') (and self.stderr if the API call or save methods fail)? 

Also, I think your if statements would be clearer if they were nested:
```
if found:
   pop org from GH list
   if cti-contributor == False:
      toggle and save
else:
    if cti-contributor == True:
        toggle and save    
```
-----

I would like the script to create new orgs if there is anything left over once you have looped through the orgs currently in our database. That will help us discover new orgs using the 'civictechindex' tag. But we should discuss this with the product team - mainly because of the 'orgs' that they want consolidated, e.g. CTI itself.

**Comment by akibrhast** [comment]
@cnk all the changes requested sounds good. I will remove logging and apply stdout writes as well as make the if statement nested.

**Comment by akibrhast** [comment]
@cnk Implemented change request as above. Ready for review

**Review by cnk — APPROVED** [review]
Excellent! thanks for the work to create new orgs when they are discovered.

**Pull request merged**
